### ISSUE TITLE
Inviqa\BehatBroadwayExtension\BroadwayExtension` extension file or class could not be located

### ISSUE THREAD

**Issue by silviuvoicu** [inviqa/BehatBroadwayExtension#1]
Hi,
I have this error Inviqa\BehatBroadwayExtension\BroadwayExtension` extension file or class could not be located  when I try bin/behat -d l or  bin/behat --init
My composer.json 
  "repositories": {
    "BehatBroadwayExtension": {
      "type": "package",
      "package": {
        "name": "inviqa/BehatBroadwayExtension",
        "version": "1.0.0",
        "source": {
          "type": "git",
          "url": "git@github.com:inviqa/BehatBroadwayExtension.git",
          "reference": "e87f744f0e471f2a228502155870a41a06dbc645"
        }
      }
    },
    "PhpSpecBroadwayExtension": {
      "type": "package",
      "package": {
        "name": "inviqa/PhpSpecBroadwayExtension",
        "version": "1.0.0",
        "source": {
          "type": "git",
          "url": "git@github.com:inviqa/PhpSpecBroadwayExtension.git",
          "reference": "5f9cb69336a0460f77faada978324731dd194a32"
        }
      }
    }
  },
  "autoload": {
    "psr-4": {
      "SuperAwesome\": "src/SuperAwesome"
    }
  },
  "require": {
    "broadway/broadway": "0.6.*@dev"
  },
  "autoload-dev": {
    "psr-4": {
      "SuperAwesome\": "spec/SuperAwesome"
    }
  },
  "require-dev": {
    "behat/behat": "3.0.x-dev",
    "phpspec/phpspec": "2.2.x-dev",
    "inviqa/BehatBroadwayExtension": "1.0.0",
    "inviqa/PhpSpecBroadwayExtension": "1.0.0"
  },
  "config": {
    "bin-dir": "bin"
  }
}

and my behat.yml

default:
   suites:
      posted:
         contexts: [ PostedContext, Inviqa\BehatBroadwayExtension\Context\BroadwayAwareContext ]
      restapi_posted:
         contexts:  [ RestApiPostedContext ]
   extensions:
      Inviqa\BehatBroadwayExtension\BroadwayExtension: ~

So what I did wrong? Thanks.

Ps:
I hope you don't mind, if I tell a word or two also about PhpSpecBroadwayExtension
I don't have any error for Inviqa\PhpSpecBroadwayExtension\Extension, I mean that I have this phpspec.yml 
suite:
   posted:
     namespace: SuperAwesome
     psr4_prefix: spec\SuperAwesome
   extensions:
      Inviqa\PhpSpecBroadwayExtension\Extension: ~

and when I do bin/phpspec describe  SuperAwesome/Blog/Domain/Model/Post/Adapter/Broadway/Post I don't have any errors and the spec is generated as an normal spec will do, so I guess this one I get right, right?

**Comment by silviuvoicu** [comment]
After adding to my project composer.json these two lines:
 "psr-0": {
      "Inviqa\BehatBroadwayExtension": "vendor/inviqa/BehatBroadwayExtension/src/",
      "Inviqa\PhpSpecBroadwayExtension": "vendor/inviqa/PhpSpecBroadwayExtension/src/"
    }
The problem goes away.
No I have to figure it out how to use it :)

**Comment by richardmiller-zz** [comment]
I does seem like there is an issue with the autoload part of this extensions composer.json. I will take a look and try and getting working so that you don't need to add those extra lines.

The phpspec set up looks fine all it does is use a different template for generating Projectors and CommandHandlers based on looking at the class name.

**Comment by silviuvoicu** [comment]
Thanks. It's definitely needs a more completed docs or examples :) 
By the way, what I was trying to do is to try to do is taking this repo as model https://github.com/dflydev/es-cqrs-broadway-workshop and do it with behat scenarios and phpspec , just in case if looking for some examples  when this will become more suitable for packagist.org.  
Just a suggestion :)
As for phpspec extension, at least for me, I have a problem too. I will open one issue there.
